### PR TITLE
[Experimental] Support mu-law conversion for target speech

### PR DESCRIPTION
**Pull request by kan-bayashi**
This PR adds support of mu-law conversion for target speech.
This technique is used in GAN-TTS from DeepMind.
According to the paper, it helps to improve quality.

### CODE REVIEW

**Comment by kan-bayashi** [comment]
https://github.com/kan-bayashi/ParallelWaveGAN/issues/27#issuecomment-557953058

**Comment by kan-bayashi** [comment]
I tried several settings but no improvement is confirmed.
https://drive.google.com/open?id=1BrbB3Dh0c8HYxCQ5YGmXqNO-qXB0rJIB
I close this PR.

**Comment by ahmed-fau** [comment]
Hello @kan-bayashi ,

In the case of using mulaw, do you calculate the conditioning features (i.e. the melspectrogram) under this condition or you calculate the mel of the speech waveform at linear scale?

**Comment by kan-bayashi** [comment]
@ahmed-fau I used mel-spectrogram calculated in the linear domain.

**Pull request closed without merging**
