### PR TITLE
add singing vocoder and update f0 & excitation input feats

### PR DESCRIPTION
**Pull request by DrWelles**

### CODE REVIEW

**Comment by DrWelles** [comment]
1. In parallel_wavegan/bin/preprocess.py, add two pitch-related features, f0 and excitation (sin-wave-based signals).
2. In parallel_wavegan/models/uhifigan.,py, a new singing vocoder with excitation and mel as input, and a UNet-based generator.
3. In parallel_wavegan/bin/normalize.py and parallel_wavegan/bin/decode.py, add MelF0ExcitationDataset to collect mel, f0 and excitation.
4. In parallel_wavegan/bin/train.py, use a more flexible data loader for model inputs.

**Comment by ftshijt** [comment]
@kan-bayashi Hi Tomoki, as I mentioned to you days back, this is the implementation for a singing-specific vocoder. Could you please take a look to see if it fits into the repo? Many thanks!

**Comment by kan-bayashi** [comment]
Sorry for late reply, and thank you for your great PR.
I am a little bit busy in this month, I will check and revise when I finished my tasks...

**Comment by kan-bayashi** [comment]
@DrWelles I refactored your PR (see #391)
If your branch seems master, so I'm wondering to push my changes to your repo.
Is it OK?

**Comment by DrWelles** [comment]
> @DrWelles I refactored your PR (see #402) If your branch seems master, so I'm wondering to push my changes to your repo. Is it OK?

Sure

**Comment by kan-bayashi** [comment]
Thanks. I listed some points of my changes.
- I modified your codes to be compatible with all modes
- I removed duplicated codes (`evaluate_*.py`) and locate it in `bin`
- I added debug recipe of uhifigan for yesno
- I removed debug loggings
- I removed `uhifigan_single.py` since it seems not used. Is it OK?

**Comment by DrWelles** [comment]
> Thanks. I listed some points of my changes.
> 
> * I modified your codes to be compatible with all modes
> * I removed duplicated codes (`evaluate_*.py`) and locate it in `bin`
> * I added debug recipe of uhifigan for yesno
> * I removed debug loggings
> * I removed `uhifigan_single.py` since it seems not used. Is it OK?

Great! And it's OK to remove uhifigan_single.py. :)

**Comment by kan-bayashi** [comment]
Thank you so much for your great feature & sorry for late merging!

**Pull request merged**
