### PR TITLE
add recipe for kiritan & ofuton_p_utagoe db (singing voice synthesis)

### PR DESCRIPTION
**Pull request by PeterGuoRuc**
Hi, This recipe intends for training vocoder for singing voice synthesis on kiritan & ofuton_p_utagoe dataset. The vocoder can be directly used in Muskits, open-source singing voice synthesis toolkits https://github.com/SJTMusicTeam/Muskits. Pre-trained models will be uploaded to google drive soon.
Please check to see if there is anything that needs to be modified. @ftshijt @kan-bayashi

### CODE REVIEW

**Comment by kan-bayashi** [comment]
@PeterGuoRuc Thank you for your contribution! I will review today!

**Review by kan-bayashi — COMMENTED** [review]
For consistency of the naming, could you rename `kiritan` -> `kiritan_db`?

**Comment by ftshijt** [comment]
Hi @kan-bayashi , we name the recipe based on the convention of its source. While the db is regarded as the official name for both the oniku and ofuton (they are also from the same source with many overlapped songs), Kiritan seems to be a bit independent. 

In addition, we would be appreciated if following the convention in our Muskit toolkit as well (i.e., https://github.com/SJTMusicTeam/Muskits

**Comment by kan-bayashi** [comment]
OK, I see! Then that is no problem.

**Comment by kan-bayashi** [comment]
Thank you for your contribution!

**Pull request merged**
