### PR TITLE
Hubert-discrete symbol-based HiFiGAN with duration predictor

### PR DESCRIPTION
**Pull request by ftshijt**
- [x] major functions/code necessary for training
- [x] recipe for cvss_c
- [x] inference scripts for cvss_c with duration predictor

(I also apply isort to follow the style in ESPnet, please let me know if this is not needed for some reason)

### CODE REVIEW

**Comment by kan-bayashi** [comment]
Thanks, @ftshijt 

> (I also apply isort to follow the style in ESPnet, please let me know if this is not needed for some reason)

To make this PR's contribution clear, I will make another PR to apply isort.
Please wait for a while.

**Comment by kan-bayashi** [comment]
I applied isort to master. Please merge it.

**Comment by ftshijt** [comment]
Hi @kan-bayashi , may I ask for your help on the CI test? I'm not quite sure why the CI failed for the import as I'm basically following the same way as other losses.

```
parallel_wavegan/losses/__init__.py:2:1: F403 'from .duration_prediction_loss import *' used; unable to detect undefined names
parallel_wavegan/losses/__init__.py:2:1: F401 '.duration_prediction_loss.*' imported but unused
```

**Comment by kan-bayashi** [comment]
> I'm not quite sure why

Simple typo lol

**Comment by ftshijt** [comment]
I think this PR is ready. Please let me know if you have any suggestions or comments~ many thanks!

**Comment by ftshijt** [comment]
Maybe I can also put some pre-trained models into the readme?

**Review by kan-bayashi — APPROVED** [review]
Thank you for a great extension, @ftshijt.
I slightly modified your code to remove duplicated part or comments.

**Comment by kan-bayashi** [comment]
> Maybe I can also put some pre-trained models into the readme?

That is great. Please open a new PR when the model is ready.

**Comment by kan-bayashi** [comment]
If you have a time, adding a test for the hifigan with duration prediction is preferable.
Anyway, I will merge this PR at first :) Thank you again, @ftshijt.

**Pull request merged**
