### PR TITLE
Support tensorflow melgan version for speedup inference time

### PR DESCRIPTION
**Pull request by dathudeptrai**
Hi @kan-bayashi , this is the PR adds tensorflow melgan version using tf.function to optimize speed (around 2x-3x faster on CPU and GPU). The PR include code for TFMelganGenerator, notebook for convert weight from pytorch original version to tensorflow version and simple notebook to check the inference speed of tensorflow/pytorch version.

### CODE REVIEW

**Comment by kan-bayashi** [comment]
Hi @dathudeptrai.
Thank you for your great PR!
Could you remove `notebook/.ipynb_checkpoints` and add `.ipynb_checkpoints` to `.gitignore`?

**Comment by dathudeptrai** [comment]
@kan-bayashi okay :D

**Comment by kan-bayashi** [comment]
@dathudeptrai I made PR for your fork. Could you check it?
https://github.com/dathudeptrai/ParallelWaveGAN/pull/1

**Comment by kan-bayashi** [comment]
I will merge. Thanks for your great feature, @dathudeptrai!

**Comment by dathudeptrai** [comment]
hi @kan-bayashi , just curious about the performance on ur GPU :D

**Comment by kan-bayashi** [comment]
OK. I will check it later.

**Comment by xzm2004260** [comment]
hi @dathudeptrai  
get this error when this line code  “audio = TFMelGANGenerator(**config["generator_params"])(inputs)”  run ，

 InaccessibleTensorError: The tensor 'Tensor("conv2d_80/dilation_rate:0", shape=(2,), dtype=int32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=call, id=139867161584976); accessed from: FuncGraph(name=call, id=139867559519064).'

**Comment by kan-bayashi** [comment]
@dathudeptrai I tried in colab. x2.3 faster!
スクリーンショット 2020-03-18 午後11 23 13

**Comment by kan-bayashi** [comment]
I found that `.numpy()` is too slow.
スクリーンショット 2020-03-18 午後11 57 36

**Comment by dathudeptrai** [comment]
@kan-bayashi thanks for ur information. So now we can conclude that tensorflow version is faster than pytorch version around 2.X times ?, on my 2080Ti, TF is faster than pytorch 3.4 times. I also check my TF fastspeech version and got 2x faster than pytorch fastspeech. I'm planing to implement training code for fastspeech and melgan/parallelwavegan on tensorflow, since tf support pruning and sparse convnet (being implemented internally as far as i know), we will further optimize speed to 2-4 times :))

**Comment by kan-bayashi** [comment]
In colab, the speed comparison result is not consistent (there is a case where both models are almost the same). Personally, I love pytorch since the api is beautiful but in terms of the speed, it seems that tensorflow is better than pytorch.

**Comment by dathudeptrai** [comment]
Hi @kan-bayashi , not sure if u know that colab have 3 different types of GPU :v (T4: 8GB, K80: 12GB, P100: 16gb). on T4 8gb, pytorch and tf is the same but on K80 and P100, tf is faster than pytorch about 2-3x :D

**Comment by kan-bayashi** [comment]
Ah-ha. I see! Let me check it.

**Pull request merged**
